services:
    victoire_core.widget_calculator_content_resolver:
        class: Victoire\Widget\CalculatorBundle\Resolver\WidgetCalculatorContentResolver
        parent: victoire_widget.base_widget_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Calculator }

    #alias to the entity
    victoire.widget.calculator:
        class: Victoire\Widget\CalculatorBundle\Entity\WidgetCalculator

    #alias to the form
    victoire.widget.form.calculator:
        class: Victoire\Widget\CalculatorBundle\Form\WidgetCalculatorType
        tags:
            - { name: form.type , alias: victoire_widget_form_calculator }
    victoire.widget.form.calculator.variables:
        class: Victoire\Widget\CalculatorBundle\Form\VariableType
        tags:
            - { name: form.type , alias: victoire_widget_form_calculator_variable }
    victoire.widget.form.calculator.choice_value:
        class: Victoire\Widget\CalculatorBundle\Form\ChoiceValueType
        tags:
            - { name: form.type , alias: victoire_widget_form_calculator_choice_value }
    victoire.widget.form.calculator.trigger:
        class: Victoire\Widget\CalculatorBundle\Form\TriggerType
        tags:
            - { name: form.type , alias: victoire_widget_form_calculator_trigger }
